### ISSUE TITLE
Prot 1 sign eating your coins and regarding solitary escape commands

### ISSUE THREAD

**Issue by Hincoporated** [MaxlionButMyNameIsTakenSoThisIsmyName/PrisonGame#1]
when interacting with the sign in the warden's office (somewhere near that) it will add prot 1 to what you're currently holding, but if clicked again for whatever reason, it will charge you again. To fix it? Really simple, before making it charge you and add prot 1 make it check if the item the player is holding already has prot 1, and by doing so, you wont get double charged

There are 3 commands I know of that lets you escape solitary, these are /pbsettings (bertrude), /hard and /normal. When running any of these commands, check if the player is in solitary, if they are, play a sound effect (villager angry or whatever its called) and don't run the rest of the code. If they aren't make it work like normal.

**Comment by MaxlionButMyNameIsTakenSoThisIsmyName** [comment]
tbf i've never thought of a fail-safe for prot pbsettings has been fixed, and you've made me realize that the hard/normal checks uses or statements instead of and (which has been fixed) and a prot 1 fail-safe will be  implemented next reload.
