### ISSUE TITLE
new warden cooldown

### ISSUE THREAD

**Issue by Xebrax124** [MaxlionButMyNameIsTakenSoThisIsmyName/PrisonGame#15]
keep all doors locked and give the warden immunity for 30s-2m so prisoners cant get a swat set and instantly kill the warden
now it will just be a cooldown before the warden inevitably dies

**Comment by MaxlionButMyNameIsTakenSoThisIsmyName** [comment]
Elongating the cooldown won't help- The warden just needs to kill the prisoners rioting, they don't lose immunity on damaging others.
