### ISSUE TITLE
fix the "job spam" lag. /normal resets your money

### ISSUE THREAD

**Issue by Hincoporated** [MaxlionButMyNameIsTakenSoThisIsmyName/PrisonGame#2]
instead of checking if the player has the tool that the job gives, make a variable that will keep track if the player has the job item or not. When pressed a spruce sign which corresponds to a job, change that variable to 1. Upon death, change that variable to 0, upon anything that can reset your inv set it to 0, before giving you the item, check the variable, if its 1, send a chat message "You already have a/an {jobitem}", else, give them the item

Now to the second part, when doing /normal while in normal mode, instead of not doing anything, it will respawn you and reset your money (there is no way to get it back). I haven't checked the code for /hard or /normal but I guess it doesn't check if you are already in that mode. Please fix this because a lot of people might fall to this trap

**Comment by MaxlionButMyNameIsTakenSoThisIsmyName** [comment]
Normal and Hard will be fixed in the next update, hopefully.
"Job spam" Is not really big enough of an issue to be considered, but i will try to find some way.
