### ISSUE TITLE
new guard ranking system

### ISSUE THREAD

**Issue by JustARandomPerson422** [MaxlionButMyNameIsTakenSoThisIsmyName/PrisonGame#20]
first of all , I think you should change swat name because it makes no sense them being in a prisoner . maybe riot guards or something idk.
also I think it would be cool if guards had ranking system . the guard would be able to buy an upgrade with an amount of money . the amount of money would get higher with each upgrade and maybe make it so the ranking resets in each warden or maybe not idk. the rank upgrade would get better gear or a higher level of protection enchant on the armor .

also here's another random suggestion : make the lockdown sign in warden HQ play a longer noise or something or maybe make it using note blocks if possible.

**Comment by MaxlionButMyNameIsTakenSoThisIsmyName** [comment]
swat funny name
guards having personal upgrades isnt something i want to doz
lockdown sign having a noise was a bit of a mistake from my part i always forget to make noises
