### ISSUE TITLE
suggestions channel as a forum post channel in discord

### ISSUE THREAD

**Issue by Xebrax124** [MaxlionButMyNameIsTakenSoThisIsmyName/PrisonGame#21]
putting suggestions in github is annoying as hell
if you cant yet have a forum post channel you can always get a suggestions bot

i want to vote whether i like a suggestion and i want everyone to be a part of it. needing to make a github account will severely decrease the amount of suggestions we have

**Comment by MaxlionButMyNameIsTakenSoThisIsmyName** [comment]
L
