### ISSUE TITLE
Make the golden pickaxe have a function / Fix redstone ore

### ISSUE THREAD

**Issue by Hincoporated** [MaxlionButMyNameIsTakenSoThisIsmyName/PrisonGame#3]
In this link https://github.com/MaxlionButMyNameIsTakenSoThisIsmyName/PrisonGame/blob/64eb30af61a99c0f70a257b04c70195added69b5/src/main/java/prisongame/prisongame/MyListener.java#L2274

it shows that a golden pickaxe is given to a player which has bought the random items perk. This pickaxe has indeed no use, to make it have an use, I'd figure you could change it to Material.GOLDEN_PICKAXE{Damage:36,display:{Name:'[{\"text\":\"Prisoner\\'s 
 Enhanced Pickaxe\",\"italic\":false}]'},CanDestroy:[deepslate_copper_ore,deepslate_emerald_ore,deepslate_gold_ore,deepslate_lapis_ore,deepslate_redstone_ore]};

Another problem there is, redstone ore, gives nothing, even though it can be mined. Near line 653 add event.getPlayer().setCooldown(Material.GOLDEN_PICKAXE, 5); below it

and at this link https://github.com/MaxlionButMyNameIsTakenSoThisIsmyName/PrisonGame/blob/64eb30af61a99c0f70a257b04c70195added69b5/src/main/java/prisongame/prisongame/PrisonGame.java#L99

remove all duplicates and add Material.DEEPSLATE_REDSTONE_ORE,

This was a post by Raul_333

**Comment by MaxlionButMyNameIsTakenSoThisIsmyName** [comment]
the gold pickaxe is there for comedy

**Comment by Hincoporated** [comment]
fix the redstone ore atleast
