### ISSUE TITLE
Stone axe usage

### ISSUE THREAD

**Issue by Hincoporated** [MaxlionButMyNameIsTakenSoThisIsmyName/PrisonGame#4]
https://github.com/MaxlionButMyNameIsTakenSoThisIsmyName/PrisonGame/blob/64eb30af61a99c0f70a257b04c70195added69b5/src/main/java/prisongame/prisongame/MyListener.java#L1865

This link shows the lumberjack job, which only uses a wooden_axe, maybe it could also use a stone_axe (gotten from random items) and maybe give a little bit more money. To do this, add below line 1874 this code

                    if (event.getItem().getType().equals(Material.STONE_AXE)) {
                        if (!event.getPlayer().hasCooldown(Material.STONE_AXE)) {
                            event.getPlayer().setCooldown(Material.STONE_AXE, 10);
                            event.getPlayer().setCooldown(Material.WOODEN_AXE, 10);
                            event.getPlayer().playSound(event.getPlayer(), Sound.BLOCK_WOOD_BREAK, 1, 1);
                            event.getPlayer().getPersistentDataContainer().set(PrisonGame.mny, PersistentDataType.DOUBLE ,event.getPlayer().getPersistentDataContainer().getOrDefault(PrisonGame.mny, PersistentDataType.DOUBLE, 0.0)+ 2.0 * MyTask.jobm);
                        }
                    }

Where it says 2.0, it could be changed to 2.5 or 3.0 (its a stone axe, it cuts better than a wooden axe) This would not only give the stone axe a use than only pvp but also make it help you when grinding
Also make sure to add event.getPlayer().setCooldown(Material.STONE_AXE, 10); in the wooden axe code to avoid being able to use both axes 

Post made by Raul_333

**Comment by MaxlionButMyNameIsTakenSoThisIsmyName** [comment]
stone axe is for pvp
